#include "pch.h"
#include "ccalc.h"
#include <iostream>

void show_help_functions()
{
    std::cout << "=== MATHEMATICAL FUNCTIONS ===" << std::endl;
    std::cout << std::endl;
    std::cout << "Trigonometric (radians, support complex x|z):" << std::endl;
    std::cout << "  sin(x|z), cos(x|z), tg(x|z)/tan(x|z), ctg(x|z)/cot(x|z)" << std::endl;
    std::cout << "  arcsin(x|z)/asin(x|z), arccos(x|z)/acos(x|z)" << std::endl;
    std::cout << "  arctg(x|z)/atan(x|z), arcctg(x|z)/acot(x|z)" << std::endl;
    std::cout << std::endl;
    std::cout << "Trigonometric (degrees, real only):" << std::endl;
    std::cout << "  sing(x), cosg(x), tgg(x), ctgg(x)" << std::endl;
    std::cout << std::endl;
    std::cout << "Hyperbolic (support complex x|z):" << std::endl;
    std::cout << "  sinh(x|z)/sh(x|z), cosh(x|z)/ch(x|z)" << std::endl;
    std::cout << "  tanh(x|z)/th(x|z), ctanh(x|z)/cth(x|z)" << std::endl;
    std::cout << "  asinh(x|z)/arsh(x|z), acosh(x|z)/arch(x|z)" << std::endl;
    std::cout << "  atanh(x|z)/arth(x|z), acoth(x|z)/arcth(x|z)" << std::endl;
    std::cout << "  atan2(y,x)" << std::endl;
    std::cout << std::endl;
    std::cout << "Exponential & Logarithmic:" << std::endl;
    std::cout << "  exp(x|z)             - e^x (complex support)" << std::endl;
    std::cout << "  exp10(x)             - 10^x" << std::endl;
    std::cout << "  ln(x|z)/log(x|z)     - Natural log (complex support)" << std::endl;
    std::cout << "  lg(x)/log10(x)       - Base 10 log" << std::endl;
    std::cout << "  log2(x)              - Base 2 log" << std::endl;
    std::cout << "  logn(x|z,y|z)        - Base x log (complex support)" << std::endl;
    std::cout << "  sqrt(x|z)/root2(x|z) - Square root (complex support)" << std::endl;
    std::cout << "  root3(x)/cbrt(x)     - Cube root" << std::endl;
    std::cout << "  rootn(x|z,n|z)       - n-th root (complex support)" << std::endl;
    std::cout << "  pow(x|z,y|z)         - x^y (complex support)" << std::endl;
    std::cout << std::endl;
    std::cout << "Rounding & Conversion:" << std::endl;
    std::cout << "  int(x), float(n), round(x), frac(x)" << std::endl;
    std::cout << "  not(n)               - Bitwise NOT, same as ~n" << std::endl;
    std::cout << std::endl;
    std::cout << "Other:" << std::endl;
    std::cout << "  abs(x|z)      - Absolute value / Complex magnitude" << std::endl;
    std::cout << "  fact(n), n!   - Factorial" << std::endl;
    std::cout << "  prime(n)      - Smallest prime >= n" << std::endl;
    std::cout << "  min(x,y), max(x,y)" << std::endl;
    std::cout << "  hypot(x,y)    - Hypotenuse sqrt(x^2+y^2)" << std::endl;
    std::cout << "  erf(x), erfc(x)" << std::endl;
    std::cout << std::endl;
    std::cout << "Complex:" << std::endl;
    std::cout << "  cmplx(x,y)    - Create complex number" << std::endl;
    std::cout << "  re(z)         - Real part" << std::endl;
    std::cout << "  im(z)         - Imaginary part" << std::endl;
    std::cout << "  pol(z)        - Phase angle atan(im/re)" << std::endl;
    std::cout << "  Note: Use i or j for imaginary unit, last used notation is for output" << std::endl;
    std::cout << std::endl;
    std::cout << "Decibels & Engineering:" << std::endl;
    std::cout << "  db(x), adb(x), np(x), anp(x)" << std::endl;
    std::cout << "  Vout(Vref,Rh,Rl)     - Voltage divider: Vref*(Rh+Rl)/Rl" << std::endl;
    std::cout << "  ee(n,x)              - E series of preferred numbers" << std::endl;
    std::cout << "  cs(x), acs(x)        - Cross section / diameter conversion" << std::endl;
    std::cout << "  awg(n), sawg(n), aawg(x)      - American wire gauge" << std::endl;
    std::cout << "  swg(n), sswg(n), aswg(x)      - British standard wire gauge" << std::endl;
    std::cout << "  gcd(n,m), invmod(n,m)" << std::endl;
    std::cout << std::endl;
    std::cout << "Time & Random:" << std::endl;
    std::cout << "  now(n)        - Current Unix time (+/- n hours)" << std::endl;
    std::cout << "  datatime(str) - Parse datetime to Unix time" << std::endl;
    std::cout << "  timezone, daylight, tz" << std::endl;
    std::cout << "  rnd(x)        - Random value 0..x" << std::endl;
    std::cout << std::endl;
    std::cout << "Formatting:" << std::endl;
    std::cout << "  printf(fmt,...), fprn(fmt,...), prn(fmt,...)" << std::endl;
    std::cout << std::endl;
    std::cout << "Special:" << std::endl;
    std::cout << "  help(n)       - Show help page n" << std::endl;
    std::cout << "  opacity(n)    - Set window opacity (0-100)" << std::endl;
    std::cout << "  binwide(n)    - Set binary display width" << std::endl;
    std::cout << "  menu(0/1)     - Hide/Show menu" << std::endl;
    std::cout << "  vars()        - Show variables list" << std::endl;
    std::cout << "  font(n)       - Set font size" << std::endl;
    std::cout << std::endl;
    std::cout << "Note: (x|z) means complex support, (x) real only" << std::endl;
}

void show_help_operators()
{
    std::cout << "=== OPERATORS ===" << std::endl;
    std::cout << std::endl;
    std::cout << "Arithmetic (complex support on +,-,*,/):" << std::endl;
    std::cout << "  +, -                 - Also for strings (concatenation)" << std::endl;
    std::cout << "  *, /, %              - Multiplication, division, remainder" << std::endl;
    std::cout << "  **, ^                - Power (complex support)" << std::endl;
    std::cout << "  ++, --               - Increment/Decrement (prefix & postfix)" << std::endl;
    std::cout << std::endl;
    std::cout << "Bitwise:" << std::endl;
    std::cout << "  ~                    - Complement (complex: conjugate)" << std::endl;
    std::cout << "  &                    - Bitwise AND" << std::endl;
    std::cout << "  |                    - Bitwise OR" << std::endl;
    std::cout << "  #, ^                 - Bitwise XOR" << std::endl;
    std::cout << "  <<                   - Arithmetic shift left" << std::endl;
    std::cout << "  >>                   - Arithmetic shift right" << std::endl;
    std::cout << "  >>>                  - Logical shift right" << std::endl;
    std::cout << std::endl;
    std::cout << "Comparison:" << std::endl;
    std::cout << "  ==, !=, <>           - Equal, Not equal" << std::endl;
    std::cout << "  <, <=, >, >=         - Less, Less/Equal, Greater, Greater/Equal" << std::endl;
    std::cout << std::endl;
    std::cout << "Logical:" << std::endl;
    std::cout << "  !                    - Logical NOT" << std::endl;
    std::cout << "  &&                   - Logical AND" << std::endl;
    std::cout << "  ||                   - Logical OR" << std::endl;
    std::cout << std::endl;
    std::cout << "Assignment:" << std::endl;
    std::cout << "  =                    - Simple assignment" << std::endl;
    std::cout << "  +=, -=, *=, /=, %=   - Compound assignment" << std::endl;
    std::cout << "  **=                  - Power and assign" << std::endl;
    std::cout << "  &=, |=, #=, ^=       - Bitwise compound assignment" << std::endl;
    std::cout << "  <<=, >>=, >>>=       - Shift compound assignment" << std::endl;
    std::cout << std::endl;
    std::cout << "Special:" << std::endl;
    std::cout << "  //                   - Parallel resistors: 1/(1/a+1/b)" << std::endl;
    std::cout << std::endl;
    std::cout << "Pascal mode (/PAS+):" << std::endl;
    std::cout << "  :=                   - Assignment" << std::endl;
    std::cout << "  =                    - Comparison (instead of ==)" << std::endl;
    std::cout << std::endl;
    std::cout << "C mode:" << std::endl;
    std::cout << "  =                    - Assignment" << std::endl;
    std::cout << "  ==                   - Comparison" << std::endl;
    std::cout << "  ^                    - XOR (not power!)" << std::endl;
    std::cout << "  //                   - Parallel resistors" << std::endl;
}

void show_help_formats()
{
    std::cout << "=== NUMBER FORMATS ===" << std::endl;
    std::cout << std::endl;
    std::cout << "Integer formats:" << std::endl;
    std::cout << "  0xFF, $1000          - Hexadecimal" << std::endl;
    std::cout << "  0o77, 01000          - Octal" << std::endl;
    std::cout << "  0b1010               - Binary" << std::endl;
    std::cout << "  123, -456            - Decimal" << std::endl;
    std::cout << std::endl;
    std::cout << "Float formats:" << std::endl;
    std::cout << "  3.14, -2.5, 1.23e-4  - Standard notation" << std::endl;
    std::cout << "  .5, 5.               - Partial notation" << std::endl;
    std::cout << "  1.8e6                - Normalized (1.8*10^6)" << std::endl;
    std::cout << std::endl;
    std::cout << "Scientific notation (/SCI+):" << std::endl;
    std::cout << "  1.8M = 1800000       - SI prefix (M = mega)" << std::endl;
    std::cout << "  2k5 = 2500           - Engineering notation" << std::endl;
    std::cout << "  1k33 = 1330          - Engineering notation" << std::endl;
    std::cout << std::endl;
    std::cout << "Computing notation:" << std::endl;
    std::cout << "  1KB = 1024           - Binary prefix (K = 2^10)" << std::endl;
    std::cout << "  1MB, 1GB, 1TB        - Binary multiples" << std::endl;
    std::cout << std::endl;
    std::cout << "Special formats:" << std::endl;
    std::cout << "  10`20'40\"            - Degrees/minutes/seconds" << std::endl;
    std::cout << "  1:c1:y1:d1:h1:m1:s   - Date/time format" << std::endl;
    std::cout << "  'A', 'AB'            - Character constants" << std::endl;
    std::cout << "  L'c', 'c'W           - Wide character" << std::endl;
    std::cout << "  \"string\"             - String literals" << std::endl;
    std::cout << "  \\377, \\e, \\n, \\xff  - Escape sequences" << std::endl;
    std::cout << "  3+9/64               - Fractional notation" << std::endl;
    std::cout << "  #28                  - Wire gauge (AWG)" << std::endl;
    std::cout << "  2\"5                  - Inch notation" << std::endl;
    std::cout << std::endl;
    std::cout << "Complex numbers:" << std::endl;
    std::cout << "  2+3i, -1-2i          - Rectangular form" << std::endl;
    std::cout << "  i, j                 - Imaginary unit (lowercase only!)" << std::endl;
}

void show_help_constants()
{
    std::cout << "=== PREDEFINED CONSTANTS ===" << std::endl;
    std::cout << std::endl;
    std::cout << "Mathematical:" << std::endl;
    std::cout << "  pi, PI                - π (3.14159265358979...)" << std::endl;
    std::cout << "  e, E                  - Euler's number (2.71828182845904...)" << std::endl;
    std::cout << "  phi                   - Golden ratio (1.618033988749...)" << std::endl;
    std::cout << "  i, j                  - Imaginary unit (√-1)" << std::endl;
    std::cout << std::endl;
    std::cout << "Physical Constants (CODATA 2018):" << std::endl;
    std::cout << std::endl;
    std::cout << "  Fundamental:" << std::endl;
    std::cout << "    c0                  - Speed of light in vacuum (299792458 m/s)" << std::endl;
    std::cout << "    hp                  - Planck constant (6.62607015e-34 J·s)" << std::endl;
    std::cout << "    hb                  - Reduced Planck constant ℏ (1.054571817e-34 J·s)" << std::endl;
    std::cout << "    gn                  - Gravitational constant (6.67430e-11 m³/(kg·s²))" << std::endl;
    std::cout << "    na                  - Avogadro constant (6.02214076e23 mol⁻¹)" << std::endl;
    std::cout << "    kb                  - Boltzmann constant (1.380649e-23 J/K)" << std::endl;
    std::cout << "    rg                  - Universal gas constant (8.314462618 J/(mol·K))" << std::endl;
    std::cout << std::endl;
    std::cout << "  Electromagnetic:" << std::endl;
    std::cout << "    e0                  - Electric constant (8.8541878128e-12 F/m)" << std::endl;
    std::cout << "    u0                  - Magnetic constant (1.25663706212e-6 H/m)" << std::endl;
    std::cout << "    z0                  - Impedance of vacuum (376.730313668 Ω)" << std::endl;
    std::cout << std::endl;
    std::cout << "  Particle:" << std::endl;
    std::cout << "    qe                  - Elementary charge (1.602176634e-19 C)" << std::endl;
    std::cout << "    me                  - Electron mass (9.1093837015e-31 kg)" << std::endl;
    std::cout << "    mp                  - Proton mass (1.67262192369e-27 kg)" << std::endl;
    std::cout << "    mn                  - Neutron mass (1.67492749804e-27 kg)" << std::endl;
    std::cout << "    rel                 - Classical electron radius (2.8179403262e-15 m)" << std::endl;
    std::cout << "    a0                  - Bohr radius (5.29177210903e-11 m)" << std::endl;
    std::cout << std::endl;
    std::cout << "  Astronomical:" << std::endl;
    std::cout << "    au                  - Astronomical unit (1.495978707e11 m)" << std::endl;
    std::cout << "    ly                  - Light year (9.4607304725808e15 m)" << std::endl;
    std::cout << "    pc                  - Parsec (3.0856775814914e16 m)" << std::endl;
    std::cout << std::endl;
    std::cout << "  Additional:" << std::endl;
    std::cout << "    ry                  - Rydberg constant (10973731.568160 m⁻¹)" << std::endl;
    std::cout << "    sb                  - Stefan-Boltzmann constant (5.670374419e-8 W/(m²·K⁴))" << std::endl;
    std::cout << std::endl;
    std::cout << "Integer Limits:" << std::endl;
    std::cout << "  max32, maxint         - Maximum signed 32-bit (2147483647, 0x7FFFFFFF)" << std::endl;
    std::cout << "  maxu32, maxuint       - Maximum unsigned 32-bit (4294967295, 0xFFFFFFFF)" << std::endl;
    std::cout << "  max64, maxlong        - Maximum signed 64-bit (9223372036854775807)" << std::endl;
    std::cout << "  maxu64, maxulong      - Maximum unsigned 64-bit (18446744073709551615)" << std::endl;
    std::cout << std::endl;
    std::cout << "System:" << std::endl;
    std::cout << "  version               - Calculator version" << std::endl;
    std::cout << "  timezone              - System timezone offset in hours" << std::endl;
    std::cout << "  daylight              - Daylight saving time flag (0 or 1)" << std::endl;
    std::cout << "  tz                    - Current timezone with DST applied" << std::endl;
    std::cout << std::endl;
    std::cout << "Note: Constants are predefined variables (can be changed but not recommended)." << std::endl;
    std::cout << "      All constants are case-insensitive with /UPCASE+ option." << std::endl;
}

void show_help_prefixes()
{
    std::cout << "=== SI PREFIXES (with /SCI+) ===" << std::endl;
    std::cout << std::endl;
    std::cout << "Large (decimal, power of 10):" << std::endl;
    std::cout << "  Y  - yotta  (10^24)" << std::endl;
    std::cout << "  Z  - zetta  (10^21)" << std::endl;
    std::cout << "  E  - exa    (10^18)" << std::endl;
    std::cout << "  P  - peta   (10^15)" << std::endl;
    std::cout << "  T  - tera   (10^12)" << std::endl;
    std::cout << "  G  - giga   (10^9)" << std::endl;
    std::cout << "  M  - mega   (10^6)" << std::endl;
    std::cout << "  k  - kilo   (10^3)" << std::endl;
    std::cout << "  da - deka   (10^1)" << std::endl;
    std::cout << std::endl;
    std::cout << "Small (decimal, power of 10):" << std::endl;
    std::cout << "  d  - deci   (10^-1)" << std::endl;
    std::cout << "  c  - centi  (10^-2)" << std::endl;
    std::cout << "  m  - milli  (10^-3)" << std::endl;
    std::cout << "  u  - micro  (10^-6)" << std::endl;
    std::cout << "  n  - nano   (10^-9)" << std::endl;
    std::cout << "  p  - pico   (10^-12)" << std::endl;
    std::cout << "  f  - femto  (10^-15)" << std::endl;
    std::cout << "  a  - atto   (10^-18)" << std::endl;
    std::cout << "  z  - zepto  (10^-21)" << std::endl;
    std::cout << "  y  - yocto  (10^-24)" << std::endl;
    std::cout << std::endl;
    std::cout << "Binary (power of 2):" << std::endl;
    std::cout << "  YB - yotta  (2^80)" << std::endl;
    std::cout << "  ZB - zetta  (2^70)" << std::endl;
    std::cout << "  EB - exa    (2^60)" << std::endl;
    std::cout << "  PB - peta   (2^50)" << std::endl;
    std::cout << "  TB - tera   (2^40)" << std::endl;
    std::cout << "  GB - giga   (2^30)" << std::endl;
    std::cout << "  MB - mega   (2^20)" << std::endl;
    std::cout << "  KB - kilo   (2^10)" << std::endl;
    std::cout << std::endl;
    std::cout << "Examples:" << std::endl;
    std::cout << "  5k = 5000" << std::endl;
    std::cout << "  2.5M = 2500000" << std::endl;
    std::cout << "  100u = 0.0001" << std::endl;
    std::cout << "  6k8 = 6800 (engineering notation)" << std::endl;
    std::cout << "  1KB = 1024 (binary)" << std::endl;
}

void show_help_examples()
{
    std::cout << "=== EXAMPLES ===" << std::endl;
    std::cout << std::endl;
    std::cout << "Basic arithmetic:" << std::endl;
    std::cout << "  2+2" << std::endl;
    std::cout << "  2^10" << std::endl;
    std::cout << "  sqrt(3^2+4^2)" << std::endl;
    std::cout << std::endl;
    std::cout << "Hex/Binary:" << std::endl;
    std::cout << "  0xFF + 0b1010" << std::endl;
    std::cout << "  0xDEADBEEF & 0xFF" << std::endl;
    std::cout << std::endl;
    std::cout << "Scientific notation:" << std::endl;
    std::cout << "  L:=130u;c:=2.2n;f:=1/(2*pi*sqrt(l*c))    => 297.6k" << std::endl;
    std::cout << "  72-20%                                     => 57.6" << std::endl;
    std::cout << "  72-20%+5%                                  => 60.48" << std::endl;
    std::cout << "  500*5%                                     => 12500" << std::endl;
    std::cout << "  1/2%                                       => 50" << std::endl;
    std::cout << "  57.6%%72                                   => -20" << std::endl;
    std::cout << std::endl;
    std::cout << "Complex numbers:" << std::endl;
    std::cout << "  (2+3i)*(4-5i)" << std::endl;
    std::cout << "  abs(3+4j)                                  => 5" << std::endl;
    std::cout << "  z:=3+4i                                    => 3+4i" << std::endl;
    std::cout << "  sqrt(-1)" << std::endl;
    std::cout << std::endl;
    std::cout << "Implicit multiplication (/IMUL+):" << std::endl;
    std::cout << "  2PI            (= 2*PI)" << std::endl;
    std::cout << "  2sin(PI/4)     (= 2*sin(PI/4))" << std::endl;
    std::cout << "  (1+2)(3+4)     (= (1+2)*(3+4))" << std::endl;
    std::cout << std::endl;
    std::cout << "Variables:" << std::endl;
    std::cout << "  x=5; y=10; x+y" << std::endl;
    std::cout << "  r=10; PI*r^2" << std::endl;
}

void show_help_overview()
{
    std::cout << "=== CALCULATOR HELP ===" << std::endl;
    std::cout << std::endl;
    std::cout << "Available help topics:" << std::endl;
    std::cout << "  help(0)  - This overview" << std::endl;
    std::cout << "  help(1)  - Mathematical functions" << std::endl;
    std::cout << "  help(2)  - Operators" << std::endl;
    std::cout << "  help(3)  - Number formats" << std::endl;
    std::cout << "  help(4)  - Predefined constants" << std::endl;
    std::cout << "  help(5)  - SI prefixes" << std::endl;
    std::cout << "  help(6)  - Usage examples" << std::endl;
    std::cout << "  help(7)  - Calculator options" << std::endl;
    std::cout << "  help(n)  - For any other n, shows all sections" << std::endl;
    std::cout << std::endl;
    std::cout << "Quick start:" << std::endl;
    std::cout << "  2+2                    - Simple calculation" << std::endl;
    std::cout << "  2^8                    - Power" << std::endl;
    std::cout << "  sqrt(2)                - Functions" << std::endl;
    std::cout << std::endl;
    std::cout << "Features:" << std::endl;
    std::cout << "  - C-style expressions with operators and functions" << std::endl;
    std::cout << "  - Complex number support (use i or j)" << std::endl;
    std::cout << "  - Multiple number formats (hex, octal, binary, scientific)" << std::endl;
    std::cout << "  - Variables and assignments" << std::endl;
    std::cout << "  - Implicit multiplication with /IMUL+ (2PI, 2sin(x))" << std::endl;
    std::cout << "  - SI prefixes with /SCI+ (k, M, G, m, u, n, etc.)" << std::endl;
}
void show_options_help()
{
    std::cout << "Calculator Options Help" << std::endl;
    std::cout << "=======================" << std::endl;
    std::cout << std::endl;
    std::cout << "Input/Calculation Options (WO - Write Only):" << std::endl;
    std::cout << "  /PAS+/-   - Pascal assignment and comparison style (:= =) <-> (= ==)" << std::endl;
    std::cout << "  /SCI+/-   - Scientific numbers format (2k == 2000)" << std::endl;
    std::cout << "  /UPCASE+/-- Case insensitive variables" << std::endl;
    std::cout << "  /UTMP+/-  - Using $n for temporary variables" << std::endl;
    std::cout << "  /FFLOAT+/-- Forced float mode" << std::endl;
    std::cout << "  /IMUL+/-  - Implicit multiplication (2sin(x))" << std::endl;
    std::cout << std::endl;
    std::cout << "Format Detection Flags (RO - Read Only, set by parser):" << std::endl;
    std::cout << "  /DEG+/-   - Degrees format found" << std::endl;
    std::cout << "  /SCF+/-   - Scientific (6.8k) format found" << std::endl;
    std::cout << "  /ENG+/-   - Engineering (6k8) format found" << std::endl;
    std::cout << "  /STR+/-   - String format found" << std::endl;
    std::cout << "  /HEX+/-   - Hex format found" << std::endl;
    std::cout << "  /OCT+/-   - Octal format found" << std::endl;
    std::cout << "  /FBIN+/-  - Binary format found" << std::endl;
    std::cout << "  /DAT+/-   - Date time format found" << std::endl;
    std::cout << "  /CHR+/-   - Char format found" << std::endl;
    std::cout << "  /WCH+/-   - WChar format found" << std::endl;
    std::cout << "  /ESC+/-   - Escape format found" << std::endl;
    std::cout << "  /CMP+/-   - Computing format found" << std::endl;
    std::cout << "  /UTM+/-   - Unix time format" << std::endl;
    std::cout << std::endl;
    std::cout << "Output Format Options (UI - User Interface):" << std::endl;
    std::cout << "  /NRM+/-   - Normalized output" << std::endl;
    std::cout << "  /IGR+/-   - Integer output" << std::endl;
    std::cout << "  /UNS+/-   - Unsigned output" << std::endl;
    std::cout << "  /ALL+/-   - Show all output formats" << std::endl;
    std::cout << "  /FRC+/-   - Fraction output" << std::endl;
    std::cout << "  /FRI+/-   - Fraction inch output" << std::endl;
    std::cout << "  /AUTO+/-  - Auto output format" << std::endl;
    std::cout << std::endl;
    std::cout << "UI Options:" << std::endl;
    std::cout << "  /MIN+/-   - Escape minimized feature" << std::endl;
    std::cout << "  /MNU+/-   - Show/hide menu feature" << std::endl;
    std::cout << "  /TOP+/-   - Always on top" << std::endl;
    std::cout << std::endl;
    std::cout << "Other Options:" << std::endl;
    std::cout << "  /BW=n     - Binary width (default 64)" << std::endl;
}

void show_usage()
{
    std::cout << "ccalc - Console Calculator" << std::endl;
    std::cout << "Usage:" << std::endl;
    std::cout << "  ccalc <expression> [/options]" << std::endl;
    std::cout << "  ccalc help(n)  - show help page n" << std::endl;
    std::cout << std::endl;
    std::cout << "IMPORTANT: Always use quotes around expressions!" << std::endl;
    std::cout << "  Symbols like ^, |, &, <, > have special meaning in shell." << std::endl;
    std::cout << std::endl;
    std::cout << "Examples:" << std::endl;
    std::cout << "  ccalc \"2+2\"" << std::endl;
    std::cout << "  ccalc \"2^2\"        # Power - use quotes!" << std::endl;
    std::cout << "  ccalc \"sqrt(3^2+4^2)\"" << std::endl;
    std::cout << "  ccalc \"0xFF + 0b1010\" /HEX+ /BIN+" << std::endl;
    std::cout << std::endl;
    std::cout << "Quick Options (in ccalc.cfg or command line):" << std::endl;
    std::cout << "  /PAS+/-   - Pascal style (:= =)" << std::endl;
    std::cout << "  /SCI+/-   - Scientific format (2k = 2000)" << std::endl;
    std::cout << "  /IMUL+/-  - Implicit multiplication (2sin(x))" << std::endl;
    std::cout << "  /BW=n     - Binary width (default 64)" << std::endl;
    std::cout << "  /ALL+/-   - Show all output formats" << std::endl;
    std::cout << "  /FRC+/-   - Show fraction format" << std::endl;
    std::cout << std::endl;
    std::cout << "For detailed options help, use: ccalc help(0)." << std::endl;
}
